- hosts: surveytool
  become: yes
  gather_facts: yes
  vars_files:
    - vars/main.yml
    - vars/tomcat.yml
    - local-vars/local.yml
  vars:
    tomcat_address: 127.0.0.1
    tomcat_instances:
      - name: "tomcat"
  roles:
    - role: robertdebock.tomcat
  tasks:
    - name: Setup Server Context
      template:
        src: templates/context.j2
        dest: "{{ cldr_tomcat_conf_path }}/context.xml"
        owner: root
        group: "{{ cldr_tomcat_group }}"
        mode: '0640'
      notify: Restart Tomcat
    - name: Setup Tomcat server.xml
      copy:
        src: templates/server.xml
        dest: "{{ cldr_tomcat_conf_path }}/server.xml"
        owner: root
        group: "{{ cldr_tomcat_group }}"
        mode: '0640'
      notify: Restart Tomcat
    - name: Setup Server Users
      template:
        src: templates/users.j2
        dest: "{{ cldr_tomcat_conf_path }}/tomcat-users.xml"
        owner: root
        group: "{{ cldr_tomcat_group }}"
        mode: '0640'
      notify: Restart Tomcat
    - name: Setup deploy-to-tomcat.sh
      template:
        src: templates/deploy-sh.j2
        dest: /usr/local/bin/deploy-to-tomcat.sh
        owner: root
        group: root
        mode: '0755'
  handlers:
    - name: Restart Tomcat
      service:
        name: "{{ cldr_tomcat_service }}"
        state: restarted
