name: JavaScript Tests

on:
  push:
    paths:
      - '.node-version'
      - 'tools/cldr-apps/js/**'
      - '.github/workflows/js.yml'
  pull_request:
    paths:
      - '.node-version'
      - 'tools/cldr-apps/js/**'
      - '.github/workflows/js.yml'

jobs:
  fetest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        lfs: false # not needed for this job, as we donâ€™t currently do a Java build
    - uses: nodenv/actions/node-version@v3 # setup using .node-version
    - name: Cache webpack
      uses: actions/cache@v3
      with:
        path: tools/cldr-apps/target/webpack_cache
        key: ${{ runner.os }}-webpack-${{ hashFiles('tools/cldr-apps/package*') }}-${{ hashFiles('tools/cldr-apps/src/**') }}
        restore-keys: |
          ${{ runner.os }}-webpack-
          webpack-
    - name: Cache npm repository
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-lint-${{ hashFiles('.github/workflows/js.yml') }}
        restore-keys: |
          ${{ runner.os }}-lint-
          lint-
    - name: Prepare JS tests
      run: (cd tools/cldr-apps/js && npm ci)
    - name: Run JS tests
      # stopgap: fail this if it takes too long
      timeout-minutes: 10
      run: (cd tools/cldr-apps/js && npm t)
    - name: Run Webpack production build
      run: (cd tools/cldr-apps/js && npm run build)
